import { db } from "@/lib/db";
import { getISTDate } from "@/lib/getISTDate";

export async function logAdminActivity({
    logAction,
    logMessage,
    userId = null,
    username = null,
    adminId = null,
    adminName = null,
    ipAddress = null,
    userAgent = null,
    device = null,
    browser = null,
    rawData = null,
    // createdAt = null, // Auto-generated by database
}: {
    logAction: string;
    logMessage: string;
    userId?: number | null;
    username?: string | null;
    adminId?: number | null;
    adminName?: string | null;
    ipAddress?: string | null;
    userAgent?: string | null;
    device?: string | null;
    browser?: string | null;
    rawData?: object | null;
    // createdAt?: Date | null;
}) {
    try {
        await db.adminActivityLog.create({
            data: {
                logAction,
                logMessage,
                userId,
                username,
                adminId,
                adminName,
                ipAddress,
                userAgent,
                device,
                browser,
                rawData: rawData ? JSON.stringify(rawData) : undefined,
                createdAt: getISTDate(), // IST time stored in DB
            },
        });
    } catch (error) {
        console.error("LOG_ERROR:", error);
    }
}